import compression from "compression";
import cookieParser from "cookie-parser";
import cors from "cors";
import express, { type Express } from "express";
import mongoSanitize from "express-mongo-sanitize";
import helmet from "helmet";
import hpp from "hpp";
import swaggerUi from "swagger-ui-express";
import { appointmentRouter } from "./api/appointment/appointment.router.js";
import { createAuthRouter, meRouter } from "./api/auth/auth.router.js";
import { webhookRouter } from "./api/billing/webhook.js";
import { catalogRouter } from "./api/catalog/catalog.router.js";
import { clinicalRouter } from "./api/clinical/clinical.router.js";
import { healthRouter } from "./api/health/health.router.js";
import { createInviteRouter } from "./api/invite/invite.router.js";
import { memberRouter } from "./api/member/member.router.js";
import { schedulingRouter } from "./api/schedule/schedule.router.js";
import { serviceRouter } from "./api/service/service.router.js";
import { settingsRouter } from "./api/settings/settings.router.js";
import { staffRouter } from "./api/staff/staff.router.js";
import { uploadRouter } from "./api/upload/upload.router.js";
import { visitRouter } from "./api/visit/visit.router.js";
import { NotFoundError } from "./common/errors/AppError.js";
import { correlationId } from "./common/middleware/correlationId.js";
import { errorHandler } from "./common/middleware/errorHandler.js";
import { createRateLimiter } from "./common/middleware/rateLimiter.js";
import { requestLogger } from "./common/middleware/requestLogger.js";
import { type CacheService, createCacheService } from "./common/services/cache.service.js";
import { env } from "./config/env.js";
import { swaggerSpec } from "./config/swagger.js";

export const createServer = (cache: CacheService = createCacheService()): Express => {
  const app = express();
  app.set("trust proxy", 1);
  app.use(correlationId);
  app.use(helmet());
  const origins = env.CORS_ORIGIN.split(",").map((origin) => origin.trim());
  app.use(cors({ origin: origins.includes("*") ? true : origins, credentials: true }));
  app.use(compression());
  app.use(createRateLimiter(cache));
  app.use(requestLogger);
  // Raw body for signature verification: must precede the JSON parser.
  app.use("/api/v1", webhookRouter);
  app.use(express.json({ limit: "10kb" }));
  app.use(express.urlencoded({ extended: true, limit: "10kb" }));
  app.use(cookieParser());
  app.use(mongoSanitize());
  app.use(hpp({ whitelist: ["roleIds", "status", "flags", "categoryId", "ids"] }));
  if (env.NODE_ENV !== "production")
    app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(swaggerSpec));
  app.use("/api/v1/health", healthRouter);
  app.use("/api/v1/auth", createAuthRouter(cache));
  app.use("/api/v1", meRouter);
  app.use("/api/v1", settingsRouter);
  app.use("/api/v1", createInviteRouter(cache));
  app.use("/api/v1", schedulingRouter);
  app.use("/api/v1", staffRouter);
  app.use("/api/v1", uploadRouter);
  app.use("/api/v1", serviceRouter);
  app.use("/api/v1", catalogRouter);
  app.use("/api/v1", memberRouter);
  app.use("/api/v1", appointmentRouter);
  // W8 clinical record (appended; self-contained router).
  app.use("/api/v1", clinicalRouter);
  // W9 visit workspace (appended; self-contained router). Live audio is attached in index.ts.
  app.use("/api/v1", visitRouter);
  app.use((_req, _res, next) => next(new NotFoundError("Route not found")));
  app.use(errorHandler);
  return app;
};
